#!/bin/sh
# lib should be a link to the ONI "Managed" directory with reference dlls.
mcs -lib:lib/ -r:0Harmony.dll,Assembly-CSharp-firstpass.dll,UnityEngine.dll,Assembly-CSharp.dll,UnityEngine.CoreModule.dll -t:library -out:Rusteria.dll Rusteria.cs
